const SET_PETS = "SET_PETS";
const SET_FILTERED_PETS = "SET_FILTERED_PETS";
const CLEAR_PETS = "CLEAR_PETS";
const SET_AGES = "SET_AGES";
const SET_ACTIVE_VIEW = "SET_ACTIVE_VIEW";

export {
    SET_PETS,
    CLEAR_PETS,
    SET_AGES,
    SET_ACTIVE_VIEW,
    SET_FILTERED_PETS
}